export const dataToAssign = {
  id: 0,
  codigo: "string",
  nombre: "string",
  descripcion: "string",
  visible: true,
  activo: true,
  asignado: true,
  estado: 0,
  subEstado: 0,
  // fechaReg: "2021-12-01T01:22:47.462Z",
  // fechaMod: "2021-12-01T01:22:47.462Z",
  fechaReg: new Date(),
  fechaMod: new Date(),
  usuarioMod: "string",
  usuarioReg: "string",
  idUsuarioReg: 0,
  //idUsuarioMod: 0,
  entidad: 0,
  total: 0,
  idBahia: 0,
  idsActividades: [],
};
